language: php
php:
  - 7.2
services:
  - mysql
before_script:
  - composer install
script: ./vendor/bin/phpunit ./tests
deploy:
  provider: heroku
  app: sesion6-travis-heroku-miguel
  on: master
  skip_cleanup: true
  api_key:
    secure: kv/Aa3WrU7/949rEQuOc4foVU/2VVylH5GtY+TVKjqYJG5B7d4/O+pTM4sIRDljKutgVksepyKR0eYN3JadAVwfqGNVrYKZuqfEQjMskWGvWv1Sx3JEil0s/6VQdrL/3ev2bD61Tz97hA5JvTyX+Yl+XSbAm9REUQyjutYsMZUoqmOhjZeltcTm21rKTBpPwMoTj0QVw4g6pBLNMS9sNYrW3Gwtz08CEsUbojLuHB/9K6wnAgXAZfs47fqlAHuixGmwjDJLdRMeoy9THRo90ezk3Xo5rN/or6bPnwDUdOnZNpr+pD5mhZpF9jUzZ6xujIx/346HtV6yurPzA3bKbIl0iR5boS3bicagUYNQDejUCv5r53JoFKdjpEH6ZoGqM/Xivb9xs8hJHfW2RLVYUHIOMLOwEbw5Wh1JuMU6kggTzKgbeY7IIVWwZsemFgNxYFs5WX+EVNwyCY2EMVmhGFXQcy+Lg3SpnVppWzBIT0HmKAWAg0M21Nl9l2AGMuJ8AWhR0d8IgKxYdxL4ZlKVSZQKeXNGUR9ia8hrYiqwMTOPBKcV6UmZNPKYVM4JBBA/y5S4ECpJFPBdM3Oqqg8CVOuiJD81LHfVrD1Q0BD9a9WBxCYlwhaGAF7lR7gyjuxwpx4R6BXqWTEJIIdctheU7eEkpnshRlqVSxkE6qu36lLU=
