language: php
php:
  - 7.2
services:
  - mysql
before_script:
  - composer install
script: ./vendor/bin/phpunit ./tests
deploy:
  provider: heroku
  app: sesion6-travis-heroku-miguel
  on: master
  skip_cleanup: true
  api_key:
    secure: WeGOKgSUHU9c6SkgQ83mg3E6xcIS0cWiuci2k82r0t3boZp3/WaiYJnwhyal+2RgKMCIndJOCymVp5J9Whq0jbf0gTCwCrCzSQgh84qhDrSr/35oDwfmmqNaXM5LPsQcCmw3Zms6O/ak8Ab1ZhZe1SKgwIWWnf3YTwiUYU/M66qAsJt6lYc4BTKUtU0oQwDt08t1vJtmq4Zp1P10Eazbu2kIpa7yYBVV2Qhp80UOpndANwZ0kHNZpX5DpZq1JbYQufnSp9eP84+f9GaxmrNrAJUArICuseiZAdLks9RqaNv3t1RPhdTmVMTIi9deMf/VPnyKit15Tmmrz1v4CTAjw0rUWhlMznxZLWHmnmmRGv+Mm6EgZU9Rv/CJySfGjgQQAt7afAMesmo0AE+OUoclU5ZAFJjS6QMgNVUSrKjgwOzP2bkwgJ/CQ1Gx6kp3H47S84cWh4MBJDWzFK0WrlVYPtXD1M11jYQLVppwt5WnmKH0Lsfp4keafwkNBE7AcDYjXKpaS1C8KmvV8bVe4uCjvhPZLluqBU+WJJA8p3ztJQ14gJgk41M3tAxkr6AsuDZd+FJKjjh+sPv7uXrGH3D1zQQGXwtbNB7gUHkPxOUtEvl4D2XjFvi5BclP0U/PZvNAEsyjVyI1Uqmoeb3IMkMs/rMdEhVkbTdIxTTlKIoBQIw=